apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: prod
spec:
  ports:
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30040
  selector:
    app: frontend
    namespace: prod
  type: NodePort
