apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: udacityshop-dev
  namespace: argocd

spec:
  source:
    path: kubernetes-manifests/dev
    repoURL: https://github.com/Gilles-nec/nd064_capstone_starter.git
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default

  syncPolicy:
    automated:
      prune: true
