name: Uda'CityShop [latest tag] - Package with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          
      
    - name: Build and push the Currency Service to Docker
      uses: docker/build-push-action@v2
      with:
          context: ./src/currencyservice
          file: ./src/currencyservice/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/currencyservice:latest
      
    - name: Build and push ad Service to Docker
      uses: docker/build-push-action@v2
      with:
          context: ./src/adservice
          file: ./src/adservice/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/adservice:latest
          
    - name: Build and push Product Catalog Service to Docker
      uses: docker/build-push-action@v2
      with:
          context: ./src/productcatalogservice
          file: ./src/productcatalogservice/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/productcatalogservice:latest

