name: Uda'CityShop [sha tag] - Package with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build_and_Push_Images_to_Docker_Hub:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Frontend meta
        id: frontend_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          tags: |
            type=sha
      - name: Product Catalog Service meta
        id: product_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/productcatalogservice
          tags: |
            type=sha
      - name: Currency Service meta
        id: currency_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/currencyservice
          tags: |
            type=sha
      - name: Ad Service meta
        id: ad_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/adservice
          tags: |
            type=sha
      - name: Ad Service meta
        id: ad_meta1
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/adservice-v2
          tags: |
            type=sha
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Service
        uses: docker/build-push-action@v2
        with:
          file: src/frontend/Dockerfile
          context: src/frontend
          push: true
          tags: ${{ steps.frontend_meta.outputs.tags }}
          labels: ${{ steps.frontend_meta.outputs.labels }}

      - name: Build and Push Product Catalog Service
        uses: docker/build-push-action@v2
        with:
          file: src/productcatalogservice/Dockerfile
          context: src/productcatalogservice
          push: true
          tags: ${{ steps.product_meta.outputs.tags }}
          labels: ${{ steps.product_meta.outputs.labels }}

      - name: Build and Push Currency Service Service
        uses: docker/build-push-action@v2
        with:
          file: src/currencyservice/Dockerfile
          context: src/currencyservice
          push: true
          tags: ${{ steps.currency_meta.outputs.tags }}
          labels: ${{ steps.currency_meta.outputs.labels }}

      - name: Build and Push Ad Service
        uses: docker/build-push-action@v2
        with:
          file: src/adservice/Dockerfile
          context: src/adservice
          push: true
          tags: ${{ steps.ad_meta.outputs.tags }}
          labels: ${{ steps.ad_meta.outputs.labels }}
      
      - name: Build and push Ad Service-v2
        uses: docker/build-push-action@v2
        with:
          context: src/adservice-v2
          file: src/adservice-v2/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.ad_meta1.outputs.tags }}
          labels: ${{ steps.ad_meta1.outputs.labels }}

